export enum PipelineStage {
  PROSPECT = "PROSPECT",
  SITE_SURVEY = "SITE_SURVEY",
  PRELIMINARY_QUOTE = "PRELIMINARY_QUOTE",
  DETAILED_ENGG = "DETAILED_ENGG",
  WORK_ORDER = "WORK_ORDER",
  HANDOVER_TO_EXECUTION = "HANDOVER_TO_EXECUTION",
  MATERIAL_PROCUREMENT = "MATERIAL_PROCUREMENT",
  STRUCTURE_ERECTION = "STRUCTURE_ERECTION",
  PV_PANEL_INSTALLATION = "PV_PANEL_INSTALLATION",
  AC_DC_INSTALLATION = "AC_DC_INSTALLATION",
  NET_METERING = "NET_METERING",
  FINAL_HANDOVER = "FINAL_HANDOVER"
}
